### ISSUE TITLE
PHPlike will not install on Synology 213j 

### ISSUE THREAD

**Issue by FM57** [puritys/nodejs-phplike#10]
No compiler, make command fails.

Thanks

**Comment by puritys** [comment]
Could you type "uname -a" on Synology to show the kernel version of linux?

**Comment by FM57** [comment]
Hello,

This is so great to answer ! Here it is

[image: Images intégrées 1]

I tried to install Make through opkg but I have a build issue. That version
of make does not seem compatible with the code.

Thanks in advance

Fred

2017-10-24 17:56 GMT+02:00 Jackie Chen <notifications@github.com>:

**Comment by puritys** [comment]
Sorry, I could not find out the version of linux image from the string "[image: Images intégrées 1]".
 
Could you type the following two command to show more Synology OS information.
```
cat /proc/version
dmesg | grep Linux
```

Also you could show me the error message when you install the Phplike. 
Make sure the libcurl-devel is already installed on your system if you want to compile by yourselves

**Comment by FM57** [comment]
Hi M. Chen,

Sure, anything you require !

[image: Images intégrées 1]

It seems that there is an issue with the grep function on the Synology.

As for the  libcurl-devel, it is not available on Synology though curl is
and is installed of course.

So not sure how to move from here.

Best

Fred

2017-10-25 16:00 GMT+02:00 Jackie Chen <notifications@github.com>:

**Comment by FM57** [comment]
Hello again,

And the error message below
FM57@DiskStation:/var/services/web/node.js$ sudo npm install phplike
|
> phplike@2.5.5 install /volume1/web/node.js/node_modules/phplike
> node install.js

Auto Recompile C/C++ library.

gyp WARN EACCES user "root" does not have permission to access the dev dir
"/root/.node-gyp/4.8.4"
gyp WARN EACCES attempting to reinstall using temporary dev dir
"/tmp/.node-gyp"
/volume1/web/node.js/node_modules/make/bin/make.js:7
const { existsSync: exists } = fs;
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit
(/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:211:12)
gyp ERR! System Linux 3.2.40
gyp ERR! command "/volume1/@appstore/Node.js_v4/usr/local/bin/node"
"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"rebuild"
gyp ERR! cwd /volume1/web/node.js/node_modules/phplike
gyp ERR! node -v v4.8.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

phplike@2.5.5 node_modules/phplike
├── bindings@1.3.0
├── nan@2.7.0
├── mocha@3.5.3 (browser-stdout@1.3.0, escape-string-regexp@1.0.5,
growl@1.9.2, json3@3.3.2, he@1.1.1, supports-color@3.1.2, commander@2.9.0,
diff@3.2.0, debug@2.6.8, lodash.create@3.1.1, mkdirp@0.5.1, glob@7.1.1)
└── node-gyp@3.6.2 (rimraf@2.6.2, graceful-fs@4.1.11, semver@5.3.0,
osenv@0.1.4, nopt@3.0.6, which@1.3.0, glob@7.1.2, minimatch@3.0.4,
fstream@1.0.11, mkdirp@0.5.1, tar@2.2.1, npmlog@4.1.2)
FM57@DiskStation:/var/services/web/node.js$


2017-10-25 19:56 GMT+02:00 Frederic Martin <frederic.martin57@gmail.com>:

**Comment by FM57** [comment]
And by removing folder make (fom opkg) inside node_modules


FM57@DiskStation:/var/services/web/node.js$ sudo npm install phplike
-
> phplike@2.5.5 install /volume1/web/node.js/node_modules/phplike
> node install.js

Auto Recompile C/C++ library.
make: Entering directory '/volume1/web/node.js/node_modules/phplike/build'
make: Leaving directory '/volume1/web/node.js/node_modules/phplike/build'

gyp WARN EACCES user "root" does not have permission to access the dev dir
"/root/.node-gyp/4.8.4"
gyp WARN EACCES attempting to reinstall using temporary dev dir
"/tmp/.node-gyp"
Makefile:1: /env.mak: No such file or directory
make: *** No rule to make target '/env.mak'.  Stop.
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit
(/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:211:12)
gyp ERR! System Linux 3.2.40
gyp ERR! command "/volume1/@appstore/Node.js_v4/usr/local/bin/node"
"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"rebuild"
gyp ERR! cwd /volume1/web/node.js/node_modules/phplike
gyp ERR! node -v v4.8.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

phplike@2.5.5 node_modules/phplike
├── bindings@1.3.0
├── nan@2.7.0
├── mocha@3.5.3 (escape-string-regexp@1.0.5, browser-stdout@1.3.0,
growl@1.9.2, json3@3.3.2, he@1.1.1, supports-color@3.1.2, commander@2.9.0,
diff@3.2.0, debug@2.6.8, mkdirp@0.5.1, lodash.create@3.1.1, glob@7.1.1)
└── node-gyp@3.6.2 (rimraf@2.6.2, graceful-fs@4.1.11, semver@5.3.0,
osenv@0.1.4, nopt@3.0.6, which@1.3.0, minimatch@3.0.4, glob@7.1.2,
fstream@1.0.11, mkdirp@0.5.1, tar@2.2.1, npmlog@4.1.2)
FM57@DiskStation:/var/services/web/node.js$




2017-10-26 9:29 GMT+02:00 Frederic Martin <frederic.martin57@gmail.com>:

**Comment by puritys** [comment]
You have not permission to modify dir "/root/".

Try to change the node module dir by this command:
```
npm config set prefix /volume1/web/node.js/
````

**Comment by FM57** [comment]
Hi M. Chen,

It did not work but my path was a bit different so I adapted the command to

npm config set prefix /var/services/web/node.js/

I then tried to reinstall phplike and got a different error message:

FM57@DiskStation:/var/services/web/node.js$ npm install phplike
/
> phplike@2.5.5 install /volume1/web/node.js/node_modules/phplike
> node install.js

Auto Recompile C/C++ library.
make: Entering directory '/volume1/web/node.js/node_modules/phplike/build'
make: Leaving directory '/volume1/web/node.js/node_modules/phplike/build'

Makefile:1: /env.mak: No such file or directory
make: *** No rule to make target '/env.mak'.  Stop.
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit
(/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:211:12)
gyp ERR! System Linux 3.2.40
gyp ERR! command "/volume1/@appstore/Node.js_v4/usr/local/bin/node"
"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"rebuild"
gyp ERR! cwd /volume1/web/node.js/node_modules/phplike
gyp ERR! node -v v4.8.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

phplike@2.5.5 node_modules/phplike
├── bindings@1.3.0
├── nan@2.7.0
├── mocha@3.5.3 (escape-string-regexp@1.0.5, browser-stdout@1.3.0,
growl@1.9.2, json3@3.3.2, he@1.1.1, supports-color@3.1.2, commander@2.9.0,
diff@3.2.0, debug@2.6.8, mkdirp@0.5.1, lodash.create@3.1.1, glob@7.1.1)
└── node-gyp@3.6.2 (rimraf@2.6.2, graceful-fs@4.1.11, semver@5.3.0,
osenv@0.1.4, nopt@3.0.6, which@1.3.0, minimatch@3.0.4, glob@7.1.2,
fstream@1.0.11, mkdirp@0.5.1, tar@2.2.1, npmlog@4.1.2)


I see that it tried to install into
/volume1/web/node.js/node_modules/phplike while my path is
/var/services/web/node.js/.

Is it something I can change from my end or in the phplike install script ?

Thanks much. We are making progress !

Fred

2017-10-28 10:58 GMT+02:00 Jackie Chen <notifications@github.com>:

**Comment by FM57** [comment]
I forgot to mention that I had the same message with your recommendation

FM57@DiskStation:/var/services/web/node.js$ npm config set prefix
/volume1/web/node.js/
FM57@DiskStation:/var/services/web/node.js$ npm install phplike
-
> phplike@2.5.5 install /volume1/web/node.js/node_modules/phplike
> node install.js

Auto Recompile C/C++ library.
make: Entering directory '/volume1/web/node.js/node_modules/phplike/build'
make: Leaving directory '/volume1/web/node.js/node_modules/phplike/build'

Makefile:1: /env.mak: No such file or directory
make: *** No rule to make target '/env.mak'.  Stop.
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit
(/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:211:12)
gyp ERR! System Linux 3.2.40
gyp ERR! command "/volume1/@appstore/Node.js_v4/usr/local/bin/node"
"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"rebuild"
gyp ERR! cwd /volume1/web/node.js/node_modules/phplike
gyp ERR! node -v v4.8.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

phplike@2.5.5 node_modules/phplike
├── bindings@1.3.0
├── nan@2.7.0
├── mocha@3.5.3 (escape-string-regexp@1.0.5, browser-stdout@1.3.0,
growl@1.9.2, json3@3.3.2, he@1.1.1, supports-color@3.1.2, commander@2.9.0,
diff@3.2.0, debug@2.6.8, lodash.create@3.1.1, mkdirp@0.5.1, glob@7.1.1)
└── node-gyp@3.6.2 (rimraf@2.6.2, graceful-fs@4.1.11, semver@5.3.0,
osenv@0.1.4, nopt@3.0.6, which@1.3.0, minimatch@3.0.4, glob@7.1.2,
fstream@1.0.11, mkdirp@0.5.1, tar@2.2.1, npmlog@4.1.2)


2017-10-28 11:22 GMT+02:00 Frederic Martin <frederic.martin57@gmail.com>:

**Comment by FM57** [comment]
And :)

I tried to go directly to /volume1/web/node.js. It is actually the same
path as the other. (symbolic link) ?

FM57@DiskStation:/volume1/web/node.js$

I ran again npm install phplike but still same error about the
make: *** No rule to make target '/env.mak'.  Stop.

Best Regards

Fred

2017-10-28 11:26 GMT+02:00 Frederic Martin <frederic.martin57@gmail.com>:
