### ISSUE TITLE
Not installed

### ISSUE THREAD

**Issue by ivictor777** [puritys/nodejs-phplike#11]
Mac OS X 10.13.6 High Sierra

MacBook-Pro-Viktor:.node-red admin$ node -v
v12.0.0
MacBook-Pro-Viktor:.node-red admin$ npm -v
6.9.0

MacBook-Pro-Viktor:.node-red admin$ sudo npm install -g phplike

> phplike@2.5.9 install /Users/admin/.npm-global/lib/node_modules/phplike
> node install.js

fs.js:125
    throw err;
    ^

Error: EACCES: permission denied, unlink './binary/tmp/phplike.node'
    at Object.unlinkSync (fs.js:1009:3)
    at unlink (/Users/admin/.npm-global/lib/node_modules/phplike/src/js/file.js:52:15)
    at rmdir (/Users/admin/.npm-global/lib/node_modules/phplike/src/js/file.js:43:21)
    at Object.rmdir (/Users/admin/.npm-global/lib/node_modules/phplike/src/js/file.js:41:21)
    at Object.<anonymous> (/Users/admin/.npm-global/lib/node_modules/phplike/install.js:29:30)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:826:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phplike@2.5.9 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phplike@2.5.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2019-04-25T16_56_14_591Z-debug.log
MacBook-Pro-Viktor:.node-red admin$

**Comment by ivictor777** [comment]
also not installed on Ubuntu:

![2019-04-25_20-01-35](https://user-images.githubusercontent.com/15266847/56754200-19136400-6795-11e9-9a2d-717e1c88b292.png)

**Comment by puritys** [comment]
https://github.com/puritys/nodejs-phplike/commit/8d8d2160abbe43385b11cdc21744d15f8538cc2e

Thanks your report,  I removed the legacy installation script.
The new version is 2.5.10, please try it again.
